### ISSUE TITLE
The speed of psram

### ISSUE THREAD

**Issue by Hemistic** [teknoman117/PMOD-PSRAM#1]
Hi, 
your project help me a lot! 
And I want to know  the speed of psram while using QSPI_PIO. My project needs to write data at high speed and read data at low speed. Can QSPI built with PIO fill the whole PSRAM in 1 second? I mean when the electrical connection is good. Thank you!

**Comment by teknoman117** [comment]
Hello!

It all depends on what PSRAM module you're using. I've been using the ESP-PSRAM64H for my purposes, which supports up to 133 MHz operation in QSPI and is 8 MiB in size.

To maintain maximum frequency, you must access it on a page by page basis, which in the case of this module is 1 KiB. A page write command is 8 QSPI cycles (8x 4-bit transfers - 2 for the write command, 6 for the address), plus 2048 cycles to move the page, or, 2056 cycles per 1 KiB of data. For an 8 MiB (64 Mbit) module, you need to move 8192 KiB of data, and 8192 * 2056 = 16842752 cycles. Since we have 133000000 cycles per second, you could fill the PSRAM 7.9 times per second.

It's probably better to think of this from a bandwidth perspective. In 2056 cycles we move 1024 bytes of data: 133000000 * (1024 / 2056) = 66.24 MiB/s @ 133 MHz.

I was able to achieve this on an FPGA board, but using 6-inch flying jumper wires to a Pi Pico, it wasn't stable above 33 MHz. If you had a Pico board with a PMOD connector (no flying jumper wires), you would be able to hit the maximum frequency. Just note the Pico runs at 125 MHz by default even though it's rated for 133 MHz.

Please note that the PIO example is not actually doing QSPI yet, I never ended up finishing that. However, it does work at 62.5 MHz SPI clock.

**Comment by Hemistic** [comment]
Thank you for your detailed answer！
 I think the PICO is a very interesting microcontroller, it can be overclocked up to 1GHz, and the I/O speed is outstanding, but I think you also realize that its limited SRAM limits its performance. So I think having a high-speed SRAM would be a prerequisite for it to be able to do more complex tasks, which would make it more powerful, such as logic analyzers for high storage depth, or game pad running NES games. I think PICO can be overclocked to increase its I/O speed. I have tested the flip frequency up to 200MHz. If the full speed QSPI SRAM can be realized on this basis, I believe it will be subversive. Can you imagine a 200MHz open source logic analyzer within $10?
So I was wondering if we could work together? I noticed that you are an expert in the field of FPGA, but I am really not very good at it. I have drawn many high-speed PCBs, and I also have very convenient PCB layout conditions. We can implement full-speed QSPI SRAM in one piece, and make an expansion board to implement a logic analyzer or something.
If you are not free, then I will finish it slowly by myself, but it is really troublesome for me.
